### ISSUE TITLE
Allow injection of custom annotations

### ISSUE THREAD

**Issue by tbrasser** [dNationCloud/kubernetes-jsonnet-translator#26]
Currently the generated configMaps get deleted when syncing with ArgoCD with automatic prune enabled.

Adding the following annotations will keep things working:
```
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
```

**Comment by matofeder** [comment]
Hi @tbrasser
Native support for ArgoCD is not planned yet. Anyway, nice to see that you found working solution for your use-case.
